[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings
remappings = [
    "solady/=solady/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

# Gas reporting
gas_reports = ["*"]

# RPC URLs for forking and deployment
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

# Test configuration
[profile.default.fuzz]
runs = 1000

[profile.intense.fuzz]
runs = 10000

# CI profile
[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
